spring.main.web-application-type=none
spring.application.name=memory-client

license.enabled=true
license.development.mode=false
license.bypass.enabled=false

spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftl

logging.level.daosupport=DEBUG
memory.service.url=http://127.0.0.1:9090


memory.local.datasource.driver-class-name=org.sqlite.JDBC
memory.local.datasource.file=${user.home}/.memory/memory_embedded.db
memory.local.datasource.url=jdbc:sqlite:${user.home}/.memory/memory_embedded.db
memory.local.datasource.init-resource=classpath:database/memory_embedded.db
